### ISSUE TITLE
v1.3.0 deploy problem

### ISSUE THREAD

**Issue by lanarimarco** [smeup/reload#39]
Because of a incogruency between tag v1.3.0  and version in pom.xml tagged as 1.3.0, the reload jars are never propagated as transitive dependencies. You should set version in pom as v1.3.0 and not 1.3.0. I suggest to fix it and create a new fix version v1.3.1. It was the same problem we had in the "development-SNAPSHOT" branch

**Comment by smeup** [comment]
New version v1.3.1 released.
